cf:
  butlers:
    npike: cf-butler-intelligent-kob-ip.apps.keep-716898.cf-app.com
    dhaka: cf-butler-cheerful-dog-dk.apps.dhaka.cf-app.com
  sslValidationSkipped: true

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,scheduledtasks,loggers,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

spring:
  cloud:
    config:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: cloud

  cloud:
    config:
      enabled: true
